services:
  actual-helpers:
    build:
      context: ./
      dockerfile: Dockerfile
      network: host
    env_file: .env
    volumes:
      - ./cache:/usr/src/app/cache
      - ./backup:/usr/src/app/backup
    network_mode: host